FROM alpine:latest

RUN apk add --no-cache openssh-client && \
    printf 'X' | dd of=/usr/bin/ssh bs=1 count=1 seek=0 conv=notrunc && \
    rm -f /usr/bin/ssh-copy-id && \
    chmod 0750 /usr/bin/ssh-keygen && \
    chown 12345 /usr/bin/ssh-add && \
    chgrp 12345 /usr/bin/scp

COPY build/actions_alpinelinux.test /usr/local/bin/systemintegrity-actions.test

ENTRYPOINT ["/usr/local/bin/systemintegrity-actions.test", "-test.v"]
